### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by spitschan** [DavidBrainard/OneLightToolbox#3]
`OLEstimateConePhotopigmentFractionBleached` in OneLightToolbox appears to be functionally equivalent to `GetConeFractionBleachedFromSpectrum` in SilentSubstitutionToolbox. One of these should probably go away. Any preference?

**Comment by DavidBrainard** [comment]
I have made OLEstimateConePhotopigmentFractionBleached call through to GetConeFractionBleachedFromSpectrum (and verified that the two pieces of code gave the
same output when given the same input.)

But:

A) There was a bug in GetHumanPhotoreceptorSS, because the penumbral variants were not actually multiplying by the blood transmittance for the computation of quantal isomerization sensitivities.

B) GetHumanPhotoreceptorSS now only does anything with its fractionBleached input for the three Legacy cone spectral sensitivities.  Why was this change made?  It doesn't make sense to me as a design choice, and for sure isn't documented in the routine's comments.

**Comment by spitschan** [comment]
Thanks. 

A) Good catch.

B) That the `fractionBleached` variable is not used for the spectral sensitivities based on the tabulated absorbances is due to an omission when I implemented it, i.e. there was no design behind it. This again becomes more of a conceptual question which is whether you want to operate with bleach-adjusted spectral sensitivities when you generate silent substitution modulations or whether you want to assess the effect of pigment density changes as part of the splatter calculations. I lean towards the latter, mostly because 1) the fraction bleached calculations are ball-park estimates, though the best ones we can produce, 2) you end with a set of incompatible cone sensitivities across different backgrounds.

Programatically, I agree that the `fractionBleached` input should be used. I am updating the code and will post the commit ID here when done.

**Comment by DavidBrainard** [comment]
On B.  Agreed on both counts.  The GetHumanSpectralSS routine should support this feature wherever it is possible, and we may well never want to invoke it and rather do as you say and understand its effect.

DB

**Comment by spitschan** [comment]
This now fixed in https://github.com/spitschan/SilentSubstitutionToolbox/commit/43d08882982808fa41b92ff54e3f30634a2f0949.
